# Read data from CSV

In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path("..")))
from scripts.read_data import read_data

data = read_data()
data.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,single,2nd phase - general contingent,6th choice,Animation and Multimedia Design,Daytime,Secondary education,122.0,Portuguese,Basic Ed 3rd Cycle,Other - 11th Year,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,single,International student (bachelor),2nd choice,Tourism,Daytime,Secondary education,160.0,Portuguese,Secondary Education - 12th Year or Eq.,Higher Ed - Degree,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,single,1st phase - general contingent,6th choice,Communication Design,Daytime,Secondary education,122.0,Portuguese,Basic Ed 1st Cycle (4th/5th),Basic Ed 1st Cycle (4th/5th),...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,single,2nd phase - general contingent,3rd choice,Journalism and Communication,Daytime,Secondary education,122.0,Portuguese,Basic Ed 2nd Cycle (6th–8th),Basic Ed 1st Cycle (4th/5th),...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,married,Over 23 years old,2nd choice,Social Service (evening attendance),Evening,Secondary education,100.0,Portuguese,Basic Ed 1st Cycle (4th/5th),Basic Ed 2nd Cycle (6th–8th),...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [1]:
import pandas as pd
from scripts.consts import CATEGORICAL_COLUMN_NAMES

numeric_data = data.drop(columns = CATEGORICAL_COLUMN_NAMES)

statistics = pd.DataFrame({
    "Mean": numeric_data.mean(numeric_only=True),
    "Median": numeric_data.median(numeric_only=True),
    "Min": numeric_data.min(numeric_only=True),
    "Max": numeric_data.max(numeric_only=True),
    "Standard deviation": numeric_data.std(numeric_only=True),
    "5. percentile": numeric_data.quantile(0.05, numeric_only=True),
    "95. percentile": numeric_data.quantile(0.95, numeric_only=True),
    "Missing values": numeric_data.isnull().sum()
}).T.round(2)

statistics.reset_index().to_csv("../statistics/numeric_stats.csv", index=False)

statistics

ModuleNotFoundError: No module named 'scripts.consts'

In [ ]:
categorical_data = data[CATEGORICAL_COLUMN_NAMES]

rows_count = len(categorical_data)

for column_name in CATEGORICAL_COLUMN_NAMES:
    
    counts = categorical_data[column_name].value_counts(dropna=False)
    rows = []

    for category_name, count in counts.items():
        
        share = round(count / rows_count, 4)
        percent = str(round(share * 100, 2)) + "%"
        
        rows.append({
            "Category": category_name,
            "Share": share,
            "Percent": percent
        })
        
    column_categories = pd.DataFrame(rows)
    path = f"../statistics/categorical_stats/{column_name.replace("/", " ")}.csv"
    column_categories.to_csv(path, index=False)
    
    print("===== ", column_name, " =====")
    print("Missing: ", categorical_data[column_name].isna().sum())
    print(column_categories.head())
    print()

=====  Marital status  =====
Missing:  0
            Category   Share Percent
0             single  0.8858  88.58%
1            married  0.0857   8.57%
2           divorced  0.0206   2.06%
3        facto union  0.0057   0.57%
4  legally separated  0.0014   0.14%

=====  Application mode  =====
Missing:  0
                                       Category   Share Percent
0                1st phase - general contingent  0.3861  38.61%
1                2nd phase - general contingent  0.1971  19.71%
2                             Over 23 years old  0.1774  17.74%
3                              Change of course  0.0705   7.05%
4  Technological specialization diploma holders  0.0481   4.81%

=====  Application order  =====
Missing:  0
     Category   Share Percent
0  2nd choice  0.6840   68.4%
1  3rd choice  0.1236  12.36%
2  4th choice  0.0698   6.98%
3  5th choice  0.0563   5.63%
4  6th choice  0.0348   3.48%

=====  Course  =====
Missing:  0
                       Category   Share Percent
0                       Nursing  0.1731  17.31%
1                    Management  0.0859   8.59%
2                Social Service  0.0802   8.02%
3            Veterinary Nursing  0.0762   7.62%
4  Journalism and Communication  0.0748   7.48%

=====  Daytime/evening attendance  =====
Missing:  0
  Category   Share Percent
0  Daytime  0.8908  89.08%
1  Evening  0.1092  10.92%

=====  Previous qualification  =====
Missing:  0
                              Category   Share Percent
0                  Secondary education  0.8402  84.02%
1  Basic ed 2nd cycle (6th–8th) equiv.  0.0495   4.95%
2   Basic ed 3rd cycle (9th/10th/11th)  0.0366   3.66%
3                   Higher ed - degree  0.0285   2.85%
4                                Other  0.0102   1.02%

=====  Nacionality  =====
Missing:  0
       Category   Share Percent
0    Portuguese  0.9751  97.51%
1     Brazilian  0.0086   0.86%
2     Santoméan  0.0032   0.32%
3       Spanish  0.0029   0.29%
4  Cape Verdean  0.0029   0.29%

=====  Mother's qualification  =====
Missing:  0
                                 Category   Share Percent
0  Secondary Education - 12th Year or Eq.  0.2416  24.16%
1            Basic Ed 1st Cycle (4th/5th)  0.2281  22.81%
2                      Basic Ed 3rd Cycle  0.2154  21.54%
3            Basic Ed 2nd Cycle (6th–8th)  0.1270   12.7%
4                      Higher Ed - Degree  0.0990    9.9%

=====  Father's qualification  =====
Missing:  0
                          Category   Share Percent
0     Basic Ed 1st Cycle (4th/5th)  0.2733  27.33%
1               Basic Ed 3rd Cycle  0.2188  21.88%
2  Secondary Ed - 12th Year or Eq.  0.2043  20.43%
3     Basic Ed 2nd Cycle (6th–8th)  0.1587  15.87%
4               Higher Ed - Degree  0.0637   6.37%

=====  Mother's occupation  =====
Missing:  0
                               Category   Share Percent
0                     Unskilled Workers  0.3565  35.65%
1                  Administrative Staff  0.1847  18.47%
2  Personal Services & Security Workers  0.1198  11.98%
3           Technicians and Professions  0.0793   7.93%
4                Scientific Specialists  0.0719   7.19%

=====  Father's occupation  =====
Missing:  0
                               Category   Share Percent
0                     Unskilled Workers  0.2283  22.83%
1              Skilled Industry Workers  0.1505  15.05%
2  Personal Services & Security Workers  0.1166  11.66%
3                  Administrative Staff  0.0873   8.73%
4           Technicians and Professions  0.0868   8.68%

=====  Displaced  =====
Missing:  0
  Category   Share Percent
0      Yes  0.5484  54.84%
1       No  0.4516  45.16%

=====  Educational special needs  =====
Missing:  0
  Category   Share Percent
0       No  0.9885  98.85%
1      Yes  0.0115   1.15%

=====  Debtor  =====
Missing:  0
  Category   Share Percent
0       No  0.8863  88.63%
1      Yes  0.1137  11.37%

=====  Tuition fees up to date  =====
Missing:  0
  Category   Share Percent
0      Yes  0.8807  88.07%
1       No  0.1193  11.93%

=====  Gender  =====
Missing:  0
  Category   Share Percent
0   Female  0.6483  64.83%
1     Male  0.3517  35.17%

=====  Scholarship holder  =====
Missing:  0
  Category   Share Percent
0       No  0.7516  75.16%
1      Yes  0.2484  24.84%

=====  International  =====
Missing:  0
  Category   Share Percent
0       No  0.9751  97.51%
1      Yes  0.0249   2.49%

=====  Target  =====
Missing:  0
   Category   Share Percent
0  Graduate  0.4993  49.93%
1   Dropout  0.3212  32.12%
2  Enrolled  0.1795  17.95%